import { createClientServer } from '@/lib/server/supabaseServer';
import { NextRequest, NextResponse } from 'next/server';
import { createAPILogger } from '@/lib/logger';
import { chatWithAIConstructor, validateAppConfig } from '@/lib/services/aiConstructorService';

interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export async function POST(request: NextRequest) {
  const startTime = Date.now();
  const logger = createAPILogger(request); // ✅ Initialize logger with request parameter
  
  try {
    const supabase = await createClientServer();
    
    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { messages, conversationId } = body as { messages: ChatMessage[], conversationId?: string };

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { error: 'messages array is required' },
        { status: 400 }
      );
    }

    // Get org_id if user has membership (optional for AI constructor)
    const { data: memberships } = await supabase
      .from('memberships')
      .select('org_id')
      .eq('user_id', user.id)
      .limit(1);
    
    const orgId = memberships && memberships.length > 0 ? memberships[0].org_id : null;

    // Call AI Constructor Service
    const result = await chatWithAIConstructor(messages, user.id, orgId, conversationId);

    // Validate config if generated
    if (result.appConfig) {
      const validation = validateAppConfig(result.appConfig);
      if (!validation.valid) {
        logger.error({
          userId: user.id,
          errors: validation.errors,
        }, 'Invalid app config generated by AI');
        
        // Return error to user
        return NextResponse.json({
          message: 'К сожалению, произошла ошибка при генерации конфигурации. Попробуйте ещё раз или сформулируйте иначе.',
          appConfig: null,
          isComplete: false,
        });
      }
    }

    const duration = Date.now() - startTime;
    logger.info({
      userId: user.id,
      orgId,
      messageCount: messages.length,
      hasAppConfig: !!result.appConfig,
      duration,
    }, 'AI chat processed');

    return NextResponse.json({
      message: result.message,
      appConfig: result.appConfig,
      isComplete: result.isComplete,
    });
  } catch (error: any) {
    const duration = Date.now() - startTime;
    logger.error({
      error: error.message,
      duration,
    }, 'Error in POST /api/ai/chat');
    
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

