# ============================================
# S3cmd Configuration Script for Selectel
# ============================================
#
# Creates .s3cfg configuration file for interacting
# with Selectel Object Storage from Windows.
#
# Usage:
#   .\s3cfg-setup.ps1
#

param(
    [string]$AccessKey,
    [string]$SecretKey,
    [switch]$Help
)

if ($Help) {
    Write-Host @"
S3cmd Configuration Script for Selectel

Usage:
    .\s3cfg-setup.ps1                              # Interactive mode
    .\s3cfg-setup.ps1 -AccessKey "xxx" -SecretKey "yyy"  # With parameters

After running:
    s3cmd ls                        # List buckets
    s3cmd ls s3://orbo-materials    # List files in bucket
    s3cmd put file.jpg s3://orbo-materials/  # Upload file
"@
    exit 0
}

Write-Host "============================================"
Write-Host "  S3cmd Configuration for Selectel"
Write-Host "============================================"
Write-Host ""

# Get credentials if not provided
if (-not $AccessKey) {
    $AccessKey = Read-Host "Enter Selectel Access Key ID"
}
if (-not $SecretKey) {
    $SecretKey = Read-Host "Enter Selectel Secret Access Key" -AsSecureString
    $SecretKey = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecretKey)
    )
}

# Configuration content
$s3cfg = @"
# Selectel S3 Configuration
# Generated by s3cfg-setup.ps1

[default]
access_key = $AccessKey
secret_key = $SecretKey
host_base = s3.storage.selcloud.ru
host_bucket = %(bucket)s.s3.storage.selcloud.ru
use_https = True

# Performance settings
multipart_chunk_size_mb = 15
multipart_max_chunks = 10000

# Additional settings
signature_v2 = False
signurl_use_https = True
check_ssl_certificate = True
check_ssl_hostname = True
"@

# Write configuration file
$configPath = "$env:USERPROFILE\.s3cfg"
$s3cfg | Out-File -FilePath $configPath -Encoding UTF8 -Force

Write-Host ""
Write-Host "Configuration saved to: $configPath" -ForegroundColor Green
Write-Host ""
Write-Host "Testing connection..."

# Check if s3cmd is available
if (Get-Command s3cmd -ErrorAction SilentlyContinue) {
    try {
        $result = s3cmd ls 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Connection successful!" -ForegroundColor Green
            Write-Host ""
            Write-Host "Your buckets:"
            Write-Host $result
        } else {
            Write-Host "Connection test failed. Check credentials." -ForegroundColor Yellow
            Write-Host $result
        }
    } catch {
        Write-Host "Error running s3cmd: $_" -ForegroundColor Red
    }
} else {
    Write-Host "s3cmd not found. Install it with:" -ForegroundColor Yellow
    Write-Host "  pip install s3cmd"
    Write-Host "or"
    Write-Host "  scoop install s3cmd"
    Write-Host ""
    Write-Host "After installing, test with: s3cmd ls"
}

Write-Host ""
Write-Host "Common commands:"
Write-Host "  s3cmd ls                            # List buckets"
Write-Host "  s3cmd mb s3://orbo-materials        # Create bucket"
Write-Host "  s3cmd ls s3://orbo-materials        # List files"
Write-Host "  s3cmd put file.jpg s3://bucket/     # Upload file"
Write-Host "  s3cmd get s3://bucket/file.jpg      # Download file"
Write-Host "  s3cmd sync ./folder s3://bucket/    # Sync folder"
Write-Host ""

